### ISSUE TITLE
opscode-centos-7.0 not found

### ISSUE THREAD

**Issue by icadariu** [irvingpop/rhcs7#1]
Hello Irving, 

I have tried to use your vagrant file to create a rhcs 7 cluster but it seems that there is a problem with opscode-centos-7.0 that is not found (please see bellow). Is there any way I can obtain that image ?

$ vagrant up
Bringing machine 'iscsihost' up with 'virtualbox' provider...
Bringing machine 'backend0' up with 'virtualbox' provider...
Bringing machine 'backend1' up with 'virtualbox' provider...
==> iscsihost: Box 'opscode-centos-7.0' could not be found. Attempting to find and install...
    iscsihost: Box Provider: virtualbox
    iscsihost: Box Version: >= 0
==> iscsihost: Box file was not detected as metadata. Adding it directly...
==> iscsihost: Adding box 'opscode-centos-7.0' (v0) for provider: virtualbox
    iscsihost: Downloading: opscode-centos-7.0
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

**Comment by irvingpop** [comment]
Better late than never, but they are here now: https://app.vagrantup.com/bento/boxes/centos-7.5
